### PR TITLE
Migrate aas generator to aas4j

### PR DESCRIPTION
**Pull request by bs-jokri**
This PR provides a migration from the previously used
https://github.com/admin-shell-io/java-model
to
https://github.com/eclipse-aas4j/aas4j

### CODE REVIEW

**Comment by bs-jokri** [comment]
@atextor or anyone who could help: I am currently facing the problem that, when I run the tests, I got error messages caused by Jacoco. Do you have an idea what the reason could be? 

I run maven with the 
following env
```
mvn clean package -X
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /usr/local/Cellar/maven/3.8.5/libexec
Java version: 18, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/18/libexec/openjdk.jdk/Contents/Home

```

complete stack trace here: [stacktrace.txt](https://github.com/eclipse-esmf/esmf-sdk/files/10517003/stacktrace.txt)
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:196)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:177)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:163)
	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:76)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)
	... 195 more

```

**Comment by atextor** [comment]
@bs-jokri It seems the build issues are resolved already.

**Comment by bs-jokri** [comment]
@atextor @andreas-schilling I consider this PR ready for review now. However, I needed to adjust the AAS4j version in the parent POM [1] for which I had to file a PR. As I reference DEV-SNAPSHOT now in the ESMF-SDK it prevents the sdk to build in the CI infrastructure. How should we handle such situations? Release the parent POM first and then reference the released version in the PR?

**Review by atextor — APPROVED** [review]
LGTM

**Pull request merged**
